version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/myapp/

hooks:
  BeforeInstall:
    - location: /home/ec2-user/myapp/scripts/start_container.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: /home/ec2-user/myapp/scripts/stop_container.sh
      timeout: 300
      runas: root
